language: ruby
rvm:
  - 2.1
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _site
  repo: shahcompbio/shahcompbio.github.io
  target_branch: master
  fqdn: shahlab.ca
notifications:
  email:
    recipients:
      - andrew.mcpherson@gmail.com
      - jmaanaki@bccrc.ca
    on_success: always
    on_failure: always
